-- AegisForge AI waitlist storage setup for Supabase
-- Run this in Supabase Dashboard → SQL Editor → New query → Run.

create table if not exists public.waitlist (
    id bigint generated by default as identity primary key,
    email text not null unique,
    source text not null default 'landing',
    created_at timestamptz not null default now()
);

create index if not exists waitlist_created_at_idx on public.waitlist (created_at);
create index if not exists waitlist_email_idx on public.waitlist (email);

-- Optional but recommended if Row Level Security is enabled.
-- The backend uses SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS.
alter table public.waitlist enable row level security;

-- Optional analytics table for the no-cost Preview Engine.
-- Stores what users are trying to build so you can learn which modules/templates matter most.
create table if not exists public.preview_requests (
    id bigint generated by default as identity primary key,
    idea text not null,
    project_type text not null default 'auto',
    detected_category text,
    generated_name text,
    created_at timestamptz not null default now()
);

create index if not exists preview_requests_created_at_idx on public.preview_requests (created_at desc);
create index if not exists preview_requests_category_idx on public.preview_requests (detected_category);

alter table public.preview_requests enable row level security;
