-- AegisForge AI waitlist storage setup for Supabase
-- Run this in Supabase Dashboard → SQL Editor → New query → Run.

create table if not exists public.waitlist (
    id bigint generated by default as identity primary key,
    email text not null unique,
    source text not null default 'landing',
    created_at timestamptz not null default now()
);

create index if not exists waitlist_created_at_idx on public.waitlist (created_at);
create index if not exists waitlist_email_idx on public.waitlist (email);

-- Optional but recommended if Row Level Security is enabled.
-- The backend uses SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS.
alter table public.waitlist enable row level security;
